# Generated by Django 4.2.5 on 2023-12-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
