# Generated by Django 4.2.5 on 2023-12-19 01:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='dateUpdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
