# Generated by Django 4.2.5 on 2023-12-19 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursecompetence'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompetence',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
